brs scripts should warn rather than abort

diff --git a/src/slash-bedrock/share/brs/force-symlinks b/src/slash-bedrock/share/brs/force-symlinks
--- a/src/slash-bedrock/share/brs/force-symlinks
+++ b/src/slash-bedrock/share/brs/force-symlinks
@@ -10,9 +10,9 @@
 #
 # This script will create various required symlinks.
 
-abort() {
-	echo "$@" >&2
-	exit 1
+warn() {
+	echo ""
+	echo "$script warning for $stratum: $@" >&2
 }
 
 create_symlink() {
@@ -32,24 +32,25 @@ create_symlink() {
 		# This is a particularly bad situation as there is no way this
 		# could have happened that the script knows about.  Force it
 		# through anyways.
-		rm "$src"
-		ln -s "$dst" "$src" || abort "Unable to symlink $src -> $dst"
+		rm "$src" || warn "Unable to remove problematic symlink at $src"
+		ln -s "$dst" "$src" || warn "Unable to symlink $src -> $dst"
 	elif ! [ -e "$src" ]
 	then
 		# Nothing exists where we want the symlink.  Just create it.
-		ln -sf "$dst" "$src" || abort "Unable to symlink $src -> $dst"
+		ln -s "$dst" "$src" || warn "Unable to symlink $src -> $dst"
 	elif [ -e "$src" ]
 	then
 		# Something exists at the location where we want the symlink
 		# that isn't a symlink.  Move that file/directory to where we
 		# want it to go, then create the symlink to it.
-		[ -d "$dst" ] && rm -r "$dst" || abort "Unable to symlink $src -> $dst"
-		mv "$src" "$dst" || abort "Unable to symlink $src -> $dst"
-		ln -sf "$dst" "$src" || abort "Unable to symlink $src -> $dst"
+		[ -d "$dst" ] && rm -r "$dst" || warn "Unable to remove problematic file at $dst"
+		mv "$src" "$dst" || warn "Unable to move $dst -> $src"
+		ln -sf "$dst" "$src" || warn "Unable to symlink $src -> $dst"
 	fi
 }
 
 stratum="$1"
+script="force-symlinks"
 if [ "$(bri -a $stratum)" = "$(bri -a init)" ]
 then
 	stratum_root=""
@@ -64,6 +65,6 @@ create_symlink "$stratum_root/var/run" "/run"
 # points to the wrong place.
 if [ -e "$stratum_root/etc/mtab" ] && [ "$(readlink "$stratum_root/etc/mtab")" != "/proc/mounts" ]
 then
-	rm $stratum_root/etc/mtab || abort "Unable to remove bad /etc/mtab"
+	rm $stratum_root/etc/mtab || warn "Unable to remove bad /etc/mtab"
 fi
 create_symlink "$stratum_root/etc/mtab" "/proc/mounts"
diff --git a/src/slash-bedrock/share/brs/setup-etc b/src/slash-bedrock/share/brs/setup-etc
--- a/src/slash-bedrock/share/brs/setup-etc
+++ b/src/slash-bedrock/share/brs/setup-etc
@@ -10,12 +10,13 @@
 #
 # This script will set up required Bedrock /etc files
 
-abort() {
-	echo "$@" >&2
-	exit 1
+warn() {
+	echo ""
+	echo "$script warning for $stratum: $@" >&2
 }
 
 stratum=$1
+script="setup-etc"
 if [ "$(bri -a $stratum)" = "$(bri -a init)" ]
 then
 	stratum_root=""
@@ -25,28 +26,28 @@ fi
 
 if ! [ -d "$stratum_root/etc" ]
 then
-	mkdir -p "$stratum_root/etc" || abort "Unable to setup /etc for $stratum"
+	mkdir -p "$stratum_root/etc" || warn "Unable to create $stratum_root/etc"
 fi
 
 if [ ! -r "$stratum_root/etc/bedrock_stratum" ] || [ "$(cat "$stratum_root/etc/bedrock_stratum")" != "$stratum" ]
 then
-	echo "$stratum" > "$stratum_root/etc/bedrock_stratum" || abort "Unable to setup /etc for $stratum"
-	chmod 644 "$stratum_root/etc/bedrock_stratum" || abort "Unable to setup /etc for $stratum"
+	echo "$stratum" > "$stratum_root/etc/bedrock_stratum" || warn "Unable to create $stratum_root/etc/bedrock_stratum"
+	chmod 644 "$stratum_root/etc/bedrock_stratum" || warn "Unable to set permissions on $stratum_root/etc/bedrock_stratum"
 fi
 
 if [ -e /bedrock/etc/localtime ] && [ "$(sha1sum /bedrock/etc/localtime)" != "$(sha1sum $stratum_root/etc/localtime 2>/dev/null)" ]
 then
-	cp /bedrock/etc/localtime "$stratum_root/etc/localtime" || abort "Unable to setup /etc for $stratum"
+	cp /bedrock/etc/localtime "$stratum_root/etc/localtime" || warn "Unable to copy /bedrock/etc/localtime to $stratum_root/etc/localtime"
 fi
 
 if [ -e /bedrock/etc/adjtime ] && [ "$(sha1sum /bedrock/etc/adjtime)" != "$(sha1sum $stratum_root/etc/adjtime 2>/dev/null)" ]
 then
-	cp /bedrock/etc/adjtime "$stratum_root/etc/adjtime" || abort "Unable to setup /etc for $stratum"
+	cp /bedrock/etc/adjtime "$stratum_root/etc/adjtime" || warn "Unable to copy /bedrock/etc/adjtime to $stratum_root/etc/adjtime"
 fi
 
 if [ -e $stratum_root/lib/systemd/systemd ] && [ ! -e $stratum_root/etc/systemd/system/multi-user.target.wants/ ]
 then
-	mkdir -p $stratum_root/etc/systemd/system/multi-user.target.wants/
+	mkdir -p $stratum_root/etc/systemd/system/multi-user.target.wants/ || warn "Unable to create $stratum_root/etc/systemd/system/multi-user.target.wants/"
 fi
 
 # bru does not currently know to "create" directories for multi-level items.
@@ -57,6 +58,6 @@ do
 	mount_point=$(echo $line | cut -d: -f1)
 	for dir in $(echo $line | cut -d: -f2- | awk 'BEGIN{RS=",";OFS=FS="/"} {$NF=""}1' | sed -e 's/^ *//' -e 's/ *$//g')
 	do
-		mkdir -p "$stratum_root/$mount_point/$dir"
+		mkdir -p "$stratum_root/$mount_point/$dir" || warn "Unable to create $stratum_root/$mount_point/$dir"
 	done
 done
