Bulk of 1.0alpha3 is done.  Just needs testing.

diff --git a/bedrock/bin/brl b/bedrock/bin/brl
--- a/bedrock/bin/brl
+++ b/bedrock/bin/brl
@@ -1,26 +1,28 @@
 #!/bin/sh
-
+### Bedrock Linux 1.0alpha3 Bosco
+### brl (BedRock aLl)
 # This script will run the argument in all available clients
-
-# source settings and functions
-. /opt/bedrock/etc/rc.conf
-. /opt/bedrock/lib/brfunctions
 
 # check for need to print help
 if [ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]
 then
 	echo "Usage: brl COMMAND"
+	echo ""
+	echo "brl will run COMMAND in all available clients."
+	echo ""
 	exit 0
 fi
 
-# ensure config file is available
-if [ ! -r /opt/bedrock/etc/brclients.conf ]
+# ensure brclients.conf is available
+# bri needs this below
+if [ ! -r /bedrock/etc/brclients.conf ]
 then
-	abort "Cannot read /opt/bedrock/etc/brclients.conf"
+	echo "Cannot read /bedrock/etc/brclients.conf" >&2
+	exit 1
 fi
 
 for CLIENT in $(bri -l)
 do
 	echo "brl: running commands in $CLIENT"
-	brc $CLIENT "$@"
+	brc $CLIENT $@
 done
diff --git a/bedrock/sbin/bru b/bedrock/sbin/bru
--- a/bedrock/sbin/bru
+++ b/bedrock/sbin/bru
@@ -1,84 +1,111 @@
 #!/bin/sh
-
+### Bedrock Linux 1.0alpha3 Bosco
+### bru (BedRock Update)
 # This script will run the update commands specified in
-# /opt/bedrock/etc/brclients.conf
-
-# source settings and functions
-. /opt/bedrock/etc/rc.conf
-. /opt/bedrock/lib/brfunctions
+# /bedrock/etc/brclients.conf
 
 # check for need to print help
 if [ "$1" = "-h" ] || [ "$1" = "--help" ]
 then
-	echo "Usage: bru [CLIENT_NAMES]"
+	echo "Usage: bru [ARGUMENT] [CLIENT_NAMES]"
 	echo ""
-	echo "If the first argument is -y, bru will respond \"y\" to all prompts"
+	echo "bru can be used to update clients by running the updatecmd specified"
+	echo "in /bedrock/etc/brclients.conf"
+	echo ""
+	echo "If ARGUMENT is -y, bru will respond \"y\" to all prompts"
 	echo "from update commands."
 	echo ""
-	echo "If given no arguments (other than a potential -y), bru will attempt"
-	echo "to update all the clients.  Otherwise, it will attempt to update the"
-	echo "clients given in the arguments."
+	echo "If any CLIENT_NAMES are specified, bru will only update those"
+	echo "clients.  If none are specified, bru will update all clients."
 	exit 0
 fi
 
-if [ "$1" = "-y" ]
+# ensure config file is available
+if [ ! -r /bedrock/etc/brclients.conf ]
 then
-	RESPOND_YES=/bin/true
-	shift
-else
-	RESPOND_YES=/bin/false
+	echo "Cannot read /bedrock/etc/brclients.conf" >&2
+	exit 1
 fi
 
-# ensure config file is available
-if [ ! -r /opt/bedrock/etc/brclients.conf ]
+# remove -y flag from $@
+if [ "$1" = "-y" ]
 then
-	abort "Cannot read /opt/bedrock/etc/brclients.conf"
+	RESPOND_YES="/bin/true"
+	shift
+else
+	RESPOND_YES="/bin/false"
+fi
+
+if [ -z $1 ]
+then
+	REQUESTED_CLIENTS="$(bri -l)"
+else
+	REQUESTED_CLIENTS="$@"
 fi
 
 # if given specific clients to update, ensure they are all present
-for REQUESTED_CLIENT in $@
+for REQUESTED_CLIENT in $REQUESTED_CLIENTS
 do
-	if ! brc -l | grep -q $REQUESTED_CLIENT
+	if ! bri -l | grep -q $REQUESTED_CLIENT
 	then
-		abort "Cannot find \"$REQUESTED_CLIENT\" in /opt/bedrock/etc/brclients.conf"
+		echo "Cannot find \"$REQUESTED_CLIENT\" in /bedrock/etc/brclients.conf" >&2
+		exit 1
 	fi
 done
 
+# find updatecmd for each requested client and run it, piping "y" if
+# requested.
 CLIENT=""
 OLDIFS="$IFS"
 IFS='
 '
-for LINE in $(cat /opt/bedrock/etc/brclients.conf)
+for LINE in $(cat /bedrock/etc/brclients.conf)
 do
 	IFS="$OLDIFS"
-	if linegrep "^\[.\+\]$"
+	if echo $LINE | grep -q '^\[client ".*"\]$'
 	then
 		CLIENT=""
-		if [ -z "$1" ]
-		then
-			CLIENT=$(linearg)
-		else
-			for REQUESTED_CLIENT in $@
-			do
-				if [ "$(linearg)" = "$REQUESTED_CLIENT" ]
-				then
-					CLIENT=$(linearg)
-				fi
-			done
-		fi
-		if [ ! -z "$CLIENT" ]
-		then
-			echo "bru: updating $CLIENT"
-		fi
-	elif linegrep "^update\s" && [ ! -z "$CLIENT" ]
+		POTENTIAL_CLIENT=$(echo $LINE | awk -F\" '{print$2}')
+		for CURRENT_CLIENT in $REQUESTED_CLIENTS
+		do
+			if [ "$POTENTIAL_CLIENT" = "$CURRENT_CLIENT" ]
+			then
+				CLIENT="$POTENTIAL_CLIENT"
+			fi
+		done
+	fi
+	if echo $LINE | grep -q '^\s*updatecmd\s*=' && [ -n "$CLIENT" ]
 	then
+		UPDATECMD="$(echo $LINE | awk '{$1="";$2="";print$0}')"
 		if $RESPOND_YES
 		then
-			echo "Running and accepting everything from : $(linearg)"
-			yes | brc $CLIENT $(linearg)
-		else
-			echo "Running: $(linearg)"
-			brc $CLIENT $(linearg)
+			UPDATECMD="yes | $UPDATECMD"
 		fi
+		echo "bru: updating $CLIENT"
+		echo "running: $UPDATECMD"
+		/bin/sh -c "$UPDATECMD"
+	fi
+	if echo $LINE | grep -q '^\s*framework\s*=' && [ -n "$CLIENT" ]
+	then
+		UPDATECMD=$(awk '
+			/^\[framework ".*"\]$/{
+				FRAMEWORK=substr($0,13,length($0)-14)
+			}
+			/^\[client ".*"\]$/{
+				FRAMEWORK=""
+			}
+			/^[ \t]*updatecmd[ \t]*=/ && FRAMEWORK != ""{
+				$1=""; $2=""
+				print $0
+				exit
+			}
+			' /bedrock/etc/brclients.conf)
+		if $RESPOND_YES
+		then
+			UPDATECMD="yes | $UPDATECMD"
+		fi
+		echo "bru: updating $CLIENT"
+		echo "running: $UPDATECMD"
+		/bin/sh -c "$UPDATECMD"
 	fi
 done
