fix: spaces to tabs

diff --git a/src/slash-bedrock/share/brl-fetch/distros/chimera b/src/slash-bedrock/share/brl-fetch/distros/chimera
--- a/src/slash-bedrock/share/brl-fetch/distros/chimera
+++ b/src/slash-bedrock/share/brl-fetch/distros/chimera
@@ -22,15 +22,15 @@ speed_test_url() {
 }
 
 list_mirrors() {
-   # pretty sure there's only the official one :p
-   echo "https://repo.chimera-linux.org"
+	# pretty sure there's only the official one :p
+	echo "https://repo.chimera-linux.org"
 }
 
 brl_arch_to_distro() {
 	case "${1}" in
 	"aarch64") echo "aarch64" ;;
 	"riscv64") echo "riscv64" ;;
-	"ppc64")   echo "ppc64" ;;
+	"ppc64")	echo "ppc64" ;;
 	"ppc64le") echo "ppc64le" ;;
 	"x86_64")  echo "x86_64" ;;
 	*) abort "brl does not know how to translate arch \"${1}\" to ${distro} format" ;;
@@ -58,12 +58,12 @@ list_releases() {
 fetch() {
 	step "Downloading bootstrap software"
 	url="$(find_link "${target_mirror}/apk/" "^apk-${target_arch}-.*.static")"
-   apk="$(basename ${url})"
+	apk="$(basename ${url})"
 	download "${url}" "${bootstrap_dir}/${apk}"
 
-   download "${target_mirror}/apk/sha256sums.txt" "${bootstrap_dir}/shasums"
-   [ "$(sha256sum ${bootstrap_dir}/${apk} | tr -d' ' -f1)" = "$(grep ${apk} ${bootstrap_dir}/shasums | tr -d' ' -f1)" ] \
-      || { echo "ERROR: checksums did not match"; false; }
+	download "${target_mirror}/apk/sha256sums.txt" "${bootstrap_dir}/shasums"
+	[ "$(sha256sum ${bootstrap_dir}/${apk} | tr -d' ' -f1)" = "$(grep ${apk} ${bootstrap_dir}/shasums | tr -d' ' -f1)" ] \
+		|| { echo "ERROR: checksums did not match"; false; }
 
 	step "Preparing bootstrap software"
 	chmod a+rx "${bootstrap_dir}/${apk}"
@@ -73,5 +73,5 @@ fetch() {
 	setup_chroot "${bootstrap_dir}"
 	setup_ssl "${bootstrap_dir}"
 	LC_ALL=C chroot "${bootstrap_dir}" "/${apk}" -X "${target_mirror}/${target_release}/main" -U \
-      --allow-untrusted --root "/target-root" --initdb add chimerautils base-minimal
+		--allow-untrusted --root "/target-root" --initdb add chimerautils base-minimal
 }
