Add non-native CPU architecture support

diff --git a/src/slash-bedrock/share/brl-fetch/distros/clear b/src/slash-bedrock/share/brl-fetch/distros/clear
--- a/src/slash-bedrock/share/brl-fetch/distros/clear
+++ b/src/slash-bedrock/share/brl-fetch/distros/clear
@@ -12,147 +12,111 @@
 . /bedrock/share/common-code
 trap 'fetch_abort "Unexpected error occurred."' EXIT
 
-# provides the package manager swupd.
-bootstrap_deps="os-core-update"
-
 check_supported() {
 	false
-}
-
-check_experimental() {
-	case "$(uname -m)" in
-	"x86_64") true ;;
-	*) false ;;
-	esac
-}
-
-distro_arch_name() {
-	case "$(uname -m)" in
-	"x86_64") echo "x86_64" ;;
-	*) fetch_abort "brl-fetch does not support distro/architecture pair" ;;
-	esac
-}
-
-list_mirrors() {
-	echo "https://cdn.download.clearlinux.org/"
 }
 
 speed_test_url() {
 	echo "1/Manifest.MoM.tar"
 }
 
-list_releases() {
-	echo "rolling"
+list_mirrors() {
+	echo "https://cdn.download.clearlinux.org/"
+}
+
+brl_arch_to_distro() {
+	case "${1}" in
+	"x86_64") echo "x86_64" ;;
+	*) abort "brl does not know how to translate arch \"${1}\" to ${distro:-} format" ;;
+	esac
+}
+
+list_architectures() {
+	echo "x86_64"
 }
 
 default_release() {
 	echo "rolling"
 }
 
+list_releases() {
+	echo "rolling"
+}
+
 fetch() {
-	step_init 12
-
-	if [ -z "${target_dir:-}" ]; then
-		fetch_abort "Essential variable not set"
-	fi
-
-	step "Determining name"
-	name="${flag_name:-${distro}}"
-	notice "Using ${color_strat}${name}${color_norm}"
-
-	step "Determining CPU architecture"
-	arch="$(distro_arch_name)"
-	notice "Using ${color_file}${arch}${color_norm}"
-
-	step "Determining release"
-	release="$(pick_release)"
-	notice "Using ${color_file}${release}${color_norm}"
-
-	step "Determining mirror"
-	mirror="$(pick_mirror "$(speed_test_url)")"
-	notice "Using ${color_link}${mirror}${color_norm}"
-
-	step "Making directory structure"
-	bootstrap_dir="${target_dir}/brl-bootstrap"
-	mkdir -p "${target_dir}" "${bootstrap_dir}/target-root"
-
 	step "Calculating required bootstrap packages"
-	update="$(wget -O- "${mirror}/current/latest")"
+	update="$(wget -O- "${target_mirror:-}/current/latest")"
 	notice "Using update ${update}"
-	wget -O "${bootstrap_dir}/Manifest.MoM" "${mirror}/update/${update}/Manifest.MoM" >/dev/null 2>&1
+	wget -O "${bootstrap_dir:-}/Manifest.MoM" "${target_mirror:-}/update/${update}/Manifest.MoM" >/dev/null 2>&1
 	loop=true
 	NL="
 "
-	required_bundles="${bootstrap_deps}"
+	required_bundles="os-core-update"
 	while "${loop}"; do
 		loop=false
 		for bundle in ${required_bundles}; do
-			if [ -e "${bootstrap_dir}/Manifest.${bundle}" ]; then
+			if [ -e "${bootstrap_dir:-}/Manifest.${bundle}" ]; then
 				continue
 			fi
 			loop=true
-			update="$(awk -v"bundle=${bundle}" '$0 ~ /^M/ && $4 == bundle {print $3; exit}' "${bootstrap_dir}/Manifest.MoM")"
-			wget -O "${bootstrap_dir}/Manifest.${bundle}" "${mirror}/update/${update}/Manifest.${bundle}" >/dev/null 2>&1
-			required_bundles="${required_bundles}${NL}$(awk '$1 == "includes:" {print $2}' "${bootstrap_dir}/Manifest.${bundle}")"
-			echo "${required_bundles}" | sort | uniq | grep "." >"${bootstrap_dir}/required_bundles"
+			update="$(awk -v"bundle=${bundle}" '$0 ~ /^M/ && $4 == bundle {print $3; exit}' "${bootstrap_dir:-}/Manifest.MoM")"
+			wget -O "${bootstrap_dir:-}/Manifest.${bundle}" "${target_mirror:-}/update/${update}/Manifest.${bundle}" >/dev/null 2>&1
+			required_bundles="${required_bundles}${NL}$(awk '$1 == "includes:" {print $2}' "${bootstrap_dir:-}/Manifest.${bundle}")"
+			echo "${required_bundles}" | sort | uniq | grep "." >"${bootstrap_dir:-}/required_bundles"
 			echo "x"
 		done
 	done | progress_unknown
-	required_bundles="$(cat "${bootstrap_dir}/required_bundles")"
+	required_bundles="$(cat "${bootstrap_dir:-}/required_bundles")"
 	notice "Bundles required to bootstrap swupd: $(echo "${required_bundles}" | tr '\n' ' ')"
 
 	step "Downloading bootstrap software"
 	total="$(echo "${required_bundles}" | wc -w)"
-	mkdir -p "${bootstrap_dir}/staged/"
+	mkdir -p "${bootstrap_dir:-}/staged/"
 	for bundle in ${required_bundles}; do
-		update="$(awk -v"bundle=${bundle}" '$0 ~ /^M/ && $4 == bundle {print $3; exit}' "${bootstrap_dir}/Manifest.MoM")"
-		wget -O "${bootstrap_dir}/pack-${bundle}-from-0.tar" "${mirror}/update/${update}/pack-${bundle}-from-0.tar" >/dev/null 2>&1
+		update="$(awk -v"bundle=${bundle}" '$0 ~ /^M/ && $4 == bundle {print $3; exit}' "${bootstrap_dir:-}/Manifest.MoM")"
+		wget -O "${bootstrap_dir:-}/pack-${bundle}-from-0.tar" "${target_mirror:-}/update/${update}/pack-${bundle}-from-0.tar" >/dev/null 2>&1
 		echo "x"
 	done | progress_bar "${total}"
 
 	step "Extracting bootstrap packages (1/2)"
-	for tarball in "${bootstrap_dir}/pack"*.tar; do
-		tar xf "${tarball}" -C "${bootstrap_dir}"
+	for tarball in "${bootstrap_dir:-}/pack"*.tar; do
+		tar xf "${tarball}" -C "${bootstrap_dir:-}"
 		echo "x"
 	done | progress_bar "${total}"
 
 	step "Extracting bootstrap packages (2/2)"
-	rm "${bootstrap_dir}/Manifest.MoM"
-	total="$(awk 'NF==4' "${bootstrap_dir}/Manifest."* | wc -l)"
-	awk 'NF==4' "${bootstrap_dir}/Manifest."* | while read -r line; do
+	rm "${bootstrap_dir:-}/Manifest.MoM"
+	total="$(awk 'NF==4' "${bootstrap_dir:-}/Manifest."* | wc -l)"
+	awk 'NF==4' "${bootstrap_dir:-}/Manifest."* | while read -r line; do
 		type="$(echo "${line}" | cut -d"	" -f1)"
 		if echo "${type}" | grep -q '^[DFL]'; then
 			hash="$(echo "${line}" | cut -d"	" -f2)"
 			path="$(echo "${line}" | cut -d"	" -f4-)"
-			dest="${bootstrap_dir}/${path}"
+			dest="${bootstrap_dir:-}/${path}"
 			mkdir -p "$(dirname "${dest}")"
-			cp -a "${bootstrap_dir}/staged/${hash}" "${dest}"
+			cp -a "${bootstrap_dir:-}/staged/${hash}" "${dest}"
 		fi
 		echo "x"
 	done | progress_bar "${total}"
 
 	step "Installing bootstrap packages"
-	setup_chroot "${bootstrap_dir}"
-	mount --bind "${target_dir}" "${bootstrap_dir}/target-root"
-	LC_ALL=C chroot "${bootstrap_dir}" swupd verify --install --path "/target-root" --no-scripts --manifest latest
+	setup_chroot "${bootstrap_dir:-}"
+	LC_ALL=C chroot "${bootstrap_dir:-}" swupd verify --install --path "/target-root" --no-scripts --manifest latest
 	# expansion is desired
 	# shellcheck disable=SC2086
-	LC_ALL=C chroot "${bootstrap_dir}" swupd bundle-add --path "/target-root" --no-scripts ${bootstrap_deps}
-
-	step "Removing temporary bootstrap files"
-	less_lethal_rm_rf "${bootstrap_dir}"
+	LC_ALL=C chroot "${bootstrap_dir:-}" swupd bundle-add --path "/target-root" --no-scripts "os-core-update"
 
 	step "Configuring"
 	# Setup certs
-	LC_ALL=C chroot "${target_dir}" clrtrust generate
-	mkdir -p "${target_dir}/etc/ssl"
-	ln -s /var/cache/ca-certs/anchors "${target_dir}/etc/ssl/certs"
+	LC_ALL=C chroot "${target_dir:-}" clrtrust generate
+	mkdir -p "${target_dir:-}/etc/ssl"
+	ln -s /var/cache/ca-certs/anchors "${target_dir:-}/etc/ssl/certs"
 	# Clear Linux does not populate various /etc files on which Bedrock
 	# depends, even if their corresponding package is installed.  Create
 	# them.
-	echo "# File created by Bedrock Linux during stratum fetch" >"${target_dir}/etc/profile"
-	if ! [ -e "${target_dir}/etc/zshenv" ]; then
-		mkdir -p "${target_dir}/etc/zsh/"
-		echo "# File created by Bedrock Linux during stratum fetch" >"${target_dir}/etc/zshenv"
+	echo "# File created by Bedrock Linux during stratum fetch" >"${target_dir:-}/etc/profile"
+	if ! [ -e "${target_dir:-}/etc/zshenv" ]; then
+		mkdir -p "${target_dir:-}/etc/zsh/"
+		echo "# File created by Bedrock Linux during stratum fetch" >"${target_dir:-}/etc/zshenv"
 	fi
 }
diff --git a/src/slash-bedrock/share/common-code b/src/slash-bedrock/share/common-code
--- a/src/slash-bedrock/share/common-code
+++ b/src/slash-bedrock/share/common-code
@@ -6,7 +6,7 @@
 #      modify it under the terms of the GNU General Public License
 #      version 2 as published by the Free Software Foundation.
 #
-# Copyright (c) 2016-2018 Daniel Thau <danthau@bedrocklinux.org>
+# Copyright (c) 2016-2019 Daniel Thau <danthau@bedrocklinux.org>
 
 # Print the Bedrock Linux ASCII logo.
 #
@@ -492,6 +492,201 @@ enforce_id_ranges() {
 	done
 }
 
+# List of architectures Bedrock Linux supports.
+brl_archs() {
+	cat <<EOF
+aarch64
+armv7hl
+armv7l
+mips
+mipsel
+mips64el
+ppc64le
+s390x
+x86
+x86_64
+EOF
+}
+
+#
+# Many distros have different phrasing for the same exact CPU architecture.
+# Standardize witnessed variations against Bedrock's convention.
+#
+standardize_architecture() {
+	case "${1}" in
+	aarch64 | arm64) echo "aarch64" ;;
+	armhf | armhfp | armv7h | armv7hl | armv7a) echo "armv7hl" ;;
+	arm | armel | armle | arm7 | armv7 | armv7l | armv7a_hardfp) echo "armv7l" ;;
+	mips | mipsbe | mipseb) echo "mips" ;;
+	mipsel | mipsle) echo "mipsel" ;;
+	mips64el | mips64le) echo "mips64el" ;;
+	ppc64el | ppc64le) echo "ppc64le" ;;
+	s390x) echo "s390x" ;;
+	i*86 | x86) echo "x86" ;;
+	amd64 | x86_64) echo "x86_64" ;;
+	esac
+}
+
+get_system_arch() {
+	if ! system_arch="$(standardize_architecture "$(get_attr "/bedrock/strata/bedrock/" "arch")")" || [ -z "${system_arch}" ]; then
+		system_arch="$(standardize_architecture "$(uname -m)")"
+	fi
+	if [ -z "${system_arch}" ]; then
+		abort "Unable to determine system CPU architecture"
+	fi
+	echo "${system_arch}"
+}
+
+check_arch_supported_natively() {
+	arch="${1}"
+	system_arch="$(get_system_arch)"
+	if [ "${system_arch}" = "${arch}" ]; then
+		true
+		return
+	fi
+
+	case "${system_arch}:${arch}" in
+	aarch64:armv7hl)
+		true
+		return
+		;;
+	aarch64:armv7l)
+		true
+		return
+		;;
+	armv7hl:armv7l)
+		true
+		return
+		;;
+	armv7l:armv7hl)
+		# do not want qemu registering over native
+		true
+		return
+		;;
+	x86_64:x86)
+		true
+		return
+		;;
+	esac
+
+	false
+	return
+}
+
+qemu_binary_for_arch() {
+	case "${1}" in
+	aarch64) echo "qemu-aarch64-static" ;;
+	armv7hl) echo "qemu-arm-static" ;;
+	armv7l) echo "qemu-arm-static" ;;
+	mips) echo "qemu-mips-static" ;;
+	mipsel) echo "qemu-mipsel-static" ;;
+	mips64el) echo "qemu-mips64el-static" ;;
+	ppc64le) echo "qemu-ppc64le-static" ;;
+	s390x) echo "qemu-s390x-static" ;;
+	x86) echo "qemu-i386-static" ;;
+	x86_64) echo "qemu-x86_64-static" ;;
+	esac
+}
+
+setup_binfmt_misc() {
+	stratum="${1}"
+	mount="/proc/sys/fs/binfmt_misc"
+
+	arch="$(get_attr "/bedrock/strata/${stratum}" "arch" 2>/dev/null)" || true
+
+	# If stratum is native, skip setting up binfmt_misc
+	if [ -z "${arch}" ] || check_arch_supported_natively "${arch}"; then
+		return
+	fi
+
+	# ensure module is loaded
+	if ! [ -d "${mount}" ]; then
+		modprobe binfmt_misc
+	fi
+	if ! [ -d "${mount}" ]; then
+		abort "Unable to mount binfmt_misc to register handler for ${stratum}"
+	fi
+
+	# mount binfmt_misc if it is not already mounted
+	if ! [ -r "${mount}/register" ]; then
+		mount binfmt_misc -t binfmt_misc "${mount}"
+	fi
+	if ! [ -r "${mount}/register" ]; then
+		abort "Unable to mount binfmt_misc to register handler for ${stratum}"
+	fi
+
+	# Gather information needed to register with binfmt
+	unset name
+	unset sum
+	unset reg
+	case "${arch}" in
+	aarch64)
+		name="qemu-aarch64"
+		sum="707cf2bfbdb58152fc97ed4c1643ecd16b064465"
+		reg=':qemu-aarch64:M:0:\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-aarch64-static:OC'
+		;;
+	armv7l | armv7hl)
+		name="qemu-arm"
+		sum="bbada633c3eda72c9be979357b51c0ac8edb9eba"
+		reg=':qemu-arm:M:0:\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:OC'
+		;;
+	mips)
+		name="qemu-mips"
+		sum="5751a5cf2bbc2cb081d314f4b340ca862c11b90c"
+		reg=':qemu-mips:M:0:\x7fELF\x01\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x08:\xff\xff\xff\xff\xff\xff\xff\x00\xfe\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff:/usr/bin/qemu-mips-static:OC'
+		;;
+	mipsel)
+		name="qemu-mipsel"
+		sum="2bccf248508ffd8e460b211f5f4159906754a498"
+		reg=':qemu-mipsel:M:0:\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x08\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xfe\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-mipsel-static:OC'
+		;;
+	mips64el)
+		name="qemu-mips64el"
+		sum="ed9513fa110eed9085cf21a789a55e047f660237"
+		reg=':qemu-mips64el:M:0:\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x08\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xfe\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-mips64el-static:OC'
+		;;
+	ppc64le)
+		name="qemu-ppc64le"
+		sum="b42c326e62f05cae1d412d3b5549a06228aeb409"
+		reg=':qemu-ppc64le:M:0:\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x15\x00:\xff\xff\xff\xff\xff\xff\xff\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\x00:/usr/bin/qemu-ppc64le-static:OC'
+		;;
+	s390x)
+		name="qemu-s390x"
+		sum="9aed062ea40b5388fd4dea5e5da837c157854021"
+		reg=':qemu-s390x:M:0:\x7fELF\x02\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x16:\xff\xff\xff\xff\xff\xff\xff\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff:/usr/bin/qemu-s390x-static:OC'
+		;;
+	# x86)
+	# TODO: Tests with i686 failed.  Determine if i586 and i686 require different registration, and if so, their registration values.
+	# 	echo ':qemu-i386:M:0:\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x03\x00:\xff\xff\xff\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\xfe\xff\xff\xff:/usr/bin/qemu-i386-static:OC' >"${mount}/register" 2>/dev/null || true
+	# 	echo '1' >"${mount}/qemu-i386"
+	# 	echo ':qemu-i486:M:0:\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x06\x00:\xff\xff\xff\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\xfe\xff\xff\xff:/usr/bin/qemu-i386-static:OC' >"${mount}/register" 2>/dev/null || true
+	# 	echo '1' >"${mount}/qemu-i486"
+	# 	;;
+	x86_64)
+		name="qemu-x86_64"
+		sum="823c58bdb19743335c68d036fdc795e3be57e243"
+		reg=':qemu-x86_64:M:0:\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x3e\x00:\xff\xff\xff\xff\xff\xfe\xfe\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-x86_64-static:OC'
+		;;
+	*)
+		abort "Stratum \"${stratum}\" has unrecognized arch ${arch}"
+		;;
+	esac
+
+	# Remove registration with differing values.
+	if [ -r "${mount}/${name}" ] && [ "$(sha1sum "${mount}/${name}" | awk '{print$1}')" != "${sum}" ]; then
+		notice "Removing conflicting ${arch} binfmt registration"
+		echo '-1' >"${mount}/${name}"
+	fi
+
+	# Register if not already registered
+	if ! [ -r "${mount}/${name}" ]; then
+		echo "${reg}" >"${mount}/register"
+	fi
+	# Enable
+	printf "1" >"${mount}/${name}"
+	printf "1" >"${mount}/status"
+}
+
 # Run executable in /bedrock/libexec with init stratum.
 #
 # Requires the init stratum to be enabled, which is typically true in a
@@ -620,10 +815,11 @@ umount_r() {
 	prev_cnt=$((cur_cnt + 1))
 	while [ "${cur_cnt}" -lt "${prev_cnt}" ]; do
 		prev_cnt=${cur_cnt}
-		for mount in $(mounts_in_dir ${init_flag} "${dir}" | sort -r); do
+		for mount in $(mounts_in_dir ${init_flag} "${dir}" | sort -ru); do
 			${x_mount} --make-rprivate "${mount}" 2>/dev/null || true
 		done
-		for mount in $(mounts_in_dir ${init_flag} "${dir}" | sort -r); do
+		for mount in $(mounts_in_dir ${init_flag} "${dir}" | sort -ru); do
+			${x_mount} --make-rprivate "${mount}" 2>/dev/null || true
 			${x_umount} -l "${mount}" 2>/dev/null || true
 		done
 		cur_cnt="$(mounts_in_dir ${init_flag} "${dir}" | wc -l || true)"
