Updated brs for Nyla

diff --git a/src/slash-bedrock/sbin/brs b/src/slash-bedrock/sbin/brs
--- a/src/slash-bedrock/sbin/brs
+++ b/src/slash-bedrock/sbin/brs
@@ -1,4 +1,4 @@
-#!/bedrock/bin/busybox sh
+#!/bedrock/libexec/busybox sh
 #
 # brs (BedRock Setup)
 #
@@ -6,78 +6,47 @@
 #      modify it under the terms of the GNU General Public License
 #      version 2 as published by the Free Software Foundation.
 #
-# Copyright (c) 2012-2014 Daniel Thau <danthau@bedrocklinux.org>
+# Copyright (c) 2012-2015 Daniel Thau <danthau@bedrocklinux.org>
 
 # Abort if anything returns non-zero unexpectedly
-set -e
+# set -e
 # Abort if accessing unassigned variable
 set -u
 
 help() {
 cat <<EOF
-Usage: brs [enable|disable|reenable|update] [CLIENTS]
+Usage: brs COMMAND STRATUM
 
-brs manages enabling and disabling clients.  To enable clients, run:
-    brs enable <clients>
-To disable:
-    brs disable <clients>
-To disable then reenable:
-    brs reenable <clients>
-If config/frameworks have changed since a client was enabled, if one would like
-to add new mount items to a running client without disabling it, one can do
-this like so:
-    brs update <clients>
-Note that \`brs update\` may miss things such as subshare items and new
-components of a union item.
+COMMANDS:
+
+General commands:
+   enable       Enables stratum.  Stratum must be disabled.
+   disable      Disables stratum.  May be run on partially disabled stratum to
+                complete disabling it.
+   reenable     Disables then enables stratum.
+   update       Enables missing mounts in stratum.  Useful to enable newly added
+                strata.conf line without having to disable stratum.
+
+These are called automatically when appropriate.  Generally you do not want to
+run these directly.
+   force-enable Enables stratum even if it has mount points.  Usually one should
+                reenable or update instead.
+   kill         Kills all processes provided by stratum.
+   mount        Mounts missing mount points in stratum; alias for update.
+   unmount      Unmounts all mount points in stratum.
+   postdisable  Runs predisable scripts for stratum.
+   postenable   Runs preenable scripts for stratum.
+   predisable   Runs predisable scripts for stratum.
+   preenable    Runs preenable scripts for stratum.
+   fix          Iterates over all strata, fixing some mount issues.
+                Stratum must be specified for uniformity but is ignored.
+
 EOF
 }
 
-# Overwrite previous line
-out() {
-	# clear current line
-	printf "\r"
-	echo -n ${last_out:-} | sed 's/./ /g'
-	# print new line without a newline
-	printf "\r%s" "$@"
-	# store line so we can know the length to overwrite next time
-	last_out="$@"
-}
-
-# Ensure the mount source and destination both exist.  If only one exists,
-# create the other. First arg is client, second arg is mount point
-ensure_exists() {
-	src=$2
-	dst=/bedrock/clients/$1$2
-	if [ -h $src ] || [ -h $dst ]
-	then
-		# no symlinks allowed
-		return 1
-	elif [ -e $src ] && [ -e $dst ]
-	then
-		# both exist, nothing special needs to be done
-		return 0
-	elif [ -d $src ] && ! [ -e $dst ]
-	then
-		mkdir -p $dst
-		return $?
-	elif [ -f $src ] && ! [ -e $dst ]
-	then
-		mkdir -p $(dirname $dst)
-		touch $dst
-		return $?
-	elif ! [ -e $src ] && [ -d $dst ]
-	then
-		mkdir -p $src
-		return $?
-	elif ! [ -e $src ] && [ -f $dst ]
-	then
-		mkdir -p $(dirname $src)
-		touch $src
-		return $?
-	else
-		# couldn't resolve situation
-		return 1
-	fi
+abort() {
+	echo "$1" >&2
+	exit 1
 }
 
 # Repeatedly call "body" while "status" shrinks in length.  If "status" stops
@@ -97,34 +66,13 @@ repeat_down() {
 	[ ${#current} -eq 0 ]
 }
 
-# Filters out lines which are in the "preexist" variable.
-preexist_filter() {
-	awk -v"preexist=$preexist" -F'[ :]' '
-		BEGIN {
-			$0=preexist
-			for (i=1; i<=NF; i++) {
-				a[$i]=$i
-			}
-		}
-		!($1 in a) {
-			print $0
-		}
-	'
-}
+kill_procs() {
+	stratum="$1"
+	echo -n "$indent"
+	echo -n "Killing processes in stratum $stratum... "
 
-# Disable a client
-disable() {
-	client="$1"
-
-	out "[1/6] Disabling $client: executing predisable..."
-	for exe in $(bri -c $client predisable)
-	do
-		. $exe "$client"
-	done
-
-	out "[2/6] Disabling $client: killing processes..."
 	status() {
-		bri -P "$client" | cut -d' ' -f1 | xargs
+		bri -P "$stratum" | cut -d' ' -f1 | xargs
 	}
 	body() {
 		kill $current || sleep 2 && kill -9 $current
@@ -133,13 +81,20 @@ disable() {
 	then
 		echo ""
 		echo "ERROR: Could not kill all processes"
-		echo "See bri -P $client"
-		exit 1
+		echo "See bri -P $stratum"
+		return 1
+	else
+		echo "done"
 	fi
+}
 
-	out "[3/6] Disabling $client: unmounting..."
+unmount_stratum() {
+	stratum="$1"
+	echo -n "$indent"
+	echo -n "Unmounting $stratum... "
+
 	status() {
-		bri -m $client | awk '{print "/bedrock/clients/'"$client"'"$1}' 2>/dev/null
+		bri -m $stratum | grep -v ".unmanaged/okay.$" | awk -v"stratum=$stratum" '{print "/bedrock/strata/"stratum"/"$1}' 2>/dev/null
 	}
 	body() {
 		for mount in $current
@@ -162,266 +117,316 @@ disable() {
 		then
 			echo ""
 			echo "ERROR: Could not unmount all mount points"
-			echo "See bri -m $client"
-			exit 1
-		fi
-	fi
-
-	out "[4/6] Disabling $client: double-checking..."
-	if [ "x$(bri -P "$client")x" != "xx" ]
-	then
-		echo ""
-		echo "Processes remain."
-		echo "See bri -P $client"
-		exit 1
-	fi
-	if [ "x$(bri -m "$client")x" != "xx" ]
-	then
-		echo ""
-		echo "Mounts remain."
-		echo "See bri -m $client"
-		exit 1
-	fi
-
-	out "[5/6] Disabling $client: executing postdisable..."
-	for exe in $(bri -c $client postdisable)
-	do
-		. $exe "$client"
-	done
-
-	out "[6/6] Disabling $client: setting as disabled..."
-	if [ -r "/bedrock/etc/clients.d/$client.conf" ]
-	then
-		if [ -r "/bedrock/etc/clients.d/$client.conf.disabled" ]
-		then
-			echo ""
-			echo "ERROR:"
-			echo "Config exists for both states:"
-			echo "    /bedrock/etc/clients.d/$client.conf"
-			echo "and"
-			echo "    /bedrock/etc/clients.d/$client.conf.disabled"
-			echo "This must be resolved manually."
+			echo "See bri -m $stratum"
+			return 1
 		else
-			mv /bedrock/etc/clients.d/$client.conf /bedrock/etc/clients.d/$client.conf.disabled
-			echo " done"
+			echo "done"
 		fi
 	else
-		if [ -r "/bedrock/etc/clients.d/$1.conf.disabled" ]
-		then
-			echo " done"
-		else
-			# Should be pretty unlikely this happens, but just in case.
-			echo ""
-			echo "ERROR:"
-			echo "No config exists."
-			echo "This must be resolved manually."
-		fi
+		echo "done"
 	fi
-
-	# tell brp about the change
-	echo 1 > /bedrock/brpath/reparse_config
 }
 
-# this does enable *and* update
-# difference is that enable (1) refuses to operate if client is even partially
-# enabled and (2) runs pre/post enable scripts
+ensure_mounts_exist() {
+	stratum=$1
+	src=$2
+	dst=$3
+
+	if [ -h "$src" ]
+	then
+		abort "ERROR: mounting $stratum, $src is a symlink."
+	elif [ -h "$dst" ]
+	then
+		abort "ERROR: mounting $stratum, $dst is a symlink."
+	elif [ -e "$src" ] && [ -e "$dst" ]
+	then
+		# both exist, nothing special needs to be done
+		return 0
+	elif [ -d "$src" ]
+	then
+		mkdir -p "$dst"
+		if [ "$?" -ne 0 ]
+		then
+			abort "ERROR: mounting $stratum: cannot create directory at $dst"
+		fi
+	elif [ -d "$dst" ]
+	then
+		mkdir -p "$src"
+		if [ "$?" -ne 0 ]
+		then
+			abort "ERROR: mounting $stratum: cannot create directory at $dst"
+		fi
+	elif [ -f "$src" ]
+	then
+		mkdir -p "$(dirname "$dst")" && touch "$dst"
+		if [ "$?" -ne 0 ]
+		then
+			abort "ERROR: mounting $stratum: cannot touch file at $dst"
+		fi
+	elif [ -f "$dst" ]
+	then
+		mkdir -p "$(dirname "$src")" && touch "$src"
+		if [ "$?" -ne 0 ]
+		then
+			abort "ERROR: mounting $stratum: cannot touch file at $src"
+		fi
+	else
+		abort "ERROR: mounting $stratum: unable to mount $src -> $dst, ensure both locations exist"
+	fi
+}
+
+mount_stratum() {
+	stratum="$1"
+	echo -n "$indent"
+	echo -n "Mounting $stratum... "
+
+	if [ "$(bri -a init)" = "$(bri -a "$stratum")" ]
+	then
+		stratum_root=""
+	else
+		stratum_root="/bedrock/strata/$stratum"
+	fi
+
+	if [ "$(bri -a global)" = "$(bri -a init)" ]
+	then
+		global_root=""
+	else
+		global_root="/bedrock/strata/$(bri -a global)"
+	fi
+
+IFS="
+"
+	for missing_mount in $(bri -M $stratum | awk '/expected share.$/{print$1}')
+	do
+		dst="$stratum_root$missing_mount"
+		src="$global_root$missing_mount"
+		for cfg_mount in $(bri -c $stratum share)
+		do
+			if [ -e "$stratum_root$cfg_mount" ] && [ "$(realpath "$stratum_root$cfg_mount")" = "$dst" ]
+			then
+				src="$global_root$cfg_mount"
+				break
+			fi 2>/dev/null
+		done
+		ensure_mounts_exist "$stratum" "$src" "$dst"
+		# ensure is a mount point (so we can make shared)
+		if awk -v"mount=$src" '$5 == mount {exit 1}' /proc/1/mountinfo
+		then
+			mount --bind "$src" "$src"
+		fi
+		mount --make-rshared "$src"
+		mount --rbind "$src" "$dst"
+	done
+	for missing_mount in $(bri -M $stratum | awk '/expected bind.$/{print$1}')
+	do
+		dst="$stratum_root$missing_mount"
+		src="$global_root$missing_mount"
+		for cfg_mount in $(bri -c $stratum bind)
+		do
+			if [ -e "$stratum_root$cfg_mount" ] && [ "$(realpath "$stratum_root$cfg_mount")" = "$dst" ]
+			then
+				src="$global_root$cfg_mount"
+				break
+			fi 2>/dev/null
+		done
+		ensure_mounts_exist "$stratum" "$src" "$dst"
+		mount --bind "$src" "$dst"
+		mount --make-private "$dst"
+	done
+	# union has to be after bind so init-bind /etc can be available
+	for missing_mount in $(bri -M $stratum | awk '/expected union.$/{print$1}')
+	do
+		dst="$stratum_root$missing_mount"
+		src="$global_root$missing_mount"
+		for cfg_mount in $(bri -c $stratum union | awk -F: '{print$1}')
+		do
+			if [ -e "$stratum_root$cfg_mount" ] && [ "$(realpath "$stratum_root$cfg_mount")" = "$dst" ]
+			then
+				src="$global_root$cfg_mount"
+				break
+			fi 2>/dev/null
+		done
+		if ! [ -e "$src" ] && ! mkdir -p "$dst"
+		then
+			abort "ERROR: mounting $stratum, cannot create directory at $mount"
+		fi
+		redir_files=$(bri -c $stratum union | grep "^${cfg_mount}:" | cut -d':' -f2- | awk 'BEGIN{FS="([ ,:]|\\t)+";OFS=" /"}{$1=$1;print}')
+		eval "/bedrock/sbin/bru $dst $src $redir_files &"
+	done
+
+	echo "done"
+}
+
+run_config() {
+	config="$1"
+	stratum="$2"
+
+	echo -n "$indent"
+	echo -n "Running $config for $stratum... "
+
+	result=true
+	for exe in $(bri -c "$stratum" "$config")
+	do
+		if ! . $exe "$stratum"
+		then
+			abort "ERROR: $exe failed for $config for $stratum"
+		fi
+	done
+
+	echo "done"
+}
+
+disable() {
+	stratum="$1"
+
+	if [ "$(bri -a "$stratum")" == "$(bri -a init)" ]
+	then
+		abort "ERROR: enabling/disabling init stratum disallowed"
+	elif [ "$(bri -a "$stratum")" == "$(bri -a global)" ]
+	then
+		abort "ERROR: enabling/disabling global stratum disallowed"
+	fi
+
+	echo "Disabling $stratum"
+	indent="  "
+	run_config predisable $stratum || return 1
+	kill_procs $stratum || return 1
+	unmount_stratum $stratum || return 1
+	run_config postdisable $stratum || return 1
+
+	echo -n "$indent"
+	echo -n "Setting $stratum as disabled... "
+	if [ -e /bedrock/run/enabled_strata/$stratum ]
+	then
+		rm /bedrock/run/enabled_strata/$stratum
+	fi
+	for alias in $(bri -I | awk -v"stratum=$stratum" '$3 == stratum {print$1}')
+	do
+		rm /bedrock/run/enabled_strata/$alias
+	done
+	echo "done"
+
+	echo -n "$indent"
+	echo -n "Updating brpath... "
+	echo 1 > /bedrock/brpath/reparse_config
+	echo "done"
+}
+
 enable() {
-	client="$1"
+	stratum="$1"
 
-	if [ "${2:-}" = "update" ]
-	then
-		max=5
-		cur=1
-	else
-		# doing enable, not update
-		if [ "x$(bri -m "$client")x" != "xx" ]
-		then
-			echo ""
-			echo "ERROR: $client already has mounts, refusing to continue." >&2
-			echo "Consider alternative brs command, see \`brs --help\`" >&2
-			return
-		fi
-		max=7
+	echo "Enabling $stratum"
+	indent="  "
 
-		out "[1/$max] Enabling $client: executing preenable..."
-		for exe in $(bri -c $client preenable)
-		do
-			. $exe $client
-		done
-		cur=2
-	fi
-
-	preexist="$(bri -m $client | awk -F'[ :]' '{print$1}' | xargs)"
-
-	out "[$cur/$max] Enabling $client: mounting share..."
-	cur=$(expr $cur + 1)
-	for mount in $(bri -c $client share | preexist_filter)
-	do
-		# ensure the mount point exists on both ends
-		if ! ensure_exists "$client" "$mount"
-		then
-cat <<EOF 2>&1
-
-ERROR: Problem ensuring mount point exists on both ends.
-- Are you mounting on a symlink on a symlink or some other non-normal,
-non-directory file?
-- Does the mount point exist on at least one end?
-EOF
-			return
-		fi
-		# Note we're in the core, so /proc/$$/mountinfo is the core's point of
-		# view.  We're checking to see if the core has a mount point here.  If
-		# not, we'll create one by bind-mounting a directory to itself.  This
-		# is necessary for --make-shared to work.
-		if awk -v"mount=$mount" '$5 == mount {exit 1}' /proc/$$/mountinfo
-		then
-			mount --bind "$mount" "$mount"
-		fi
-		# ensure core's copy is shared
-		mount --make-rshared "$mount"
-		mount --rbind "$mount" "/bedrock/clients/$client$mount"
-	done
-
-	out "[$cur/$max] Enabling $client: mounting bind..."
-	cur=$(expr $cur + 1)
-	for mount in $(bri -c $client bind | preexist_filter)
-	do
-		# ensure the mount point exists on both ends
-		if ! ensure_exists "$client" "$mount"
-		then
-cat <<EOF 2>&1
-
-ERROR: Problem ensuring mount point exists on both ends.
-- Are you mounting on a symlink on a symlink or some other non-normal,
-non-directory file?
-- Does the mount point exist on at least one end?
-EOF
-			return
-		fi
-		mount --bind "$mount" "/bedrock/clients/$client$mount"
-		mount --make-private "/bedrock/clients/$client$mount"
-	done
-
-	# note this needs to be after bind for self-view in /bedrock/clients
-	out "[$cur/$max] Enabling $client: mounting union..."
-	cur=$(expr $cur + 1)
-	bri -c $client union | preexist_filter | awk -v"client=$client" -F'([ ,:]|\\t)+' '
-		{
-			# mount bru at the mount point for the client
-			# e.g.: /bedrock/sbin/bru /bedrock/clients/squeeze/etc
-			cmd = "/bedrock/sbin/bru /bedrock/clients/"client$1
-			# first arg should be the client self-view (without mounts)
-			# e.g.: /bedrock/clients/squeeze/bedrock/clients/squeeze/etc
-			#       |               |                               \ self-view of /etc without mounts
-			#       |               \ squeeze chroot is here
-			#       \ absolute root
-			cmd = cmd" /bedrock/clients/"client"/bedrock/clients/"client$1
-			# second arg should be the equivalent location in the core
-			cmd = cmd" "$1
-			# remaining args are files to be redirected to the core
-			for (i=2; i<=NF; i++) {
-				cmd = cmd " /"$i
-			}
-			# background it so this process will return
-			cmd = cmd "&"
-			# run it
-			system(cmd)
-			# bru may take a fraction of a second to start if we do not
-			# wait here, the result check below will think it is not
-			# mounted
-			system("sleep .25")
-		}
-	'
-
-	out "[$cur/$max] Enabling $client: double-checking..."
-	cur=$(expr $cur + 1)
-	if ! bri -s $client | grep -q "fully mounted"
+	if [ "${2:-}" != "force" ] && [ "x$(bri -m "$stratum" | grep -v ".unmanaged/okay.$")x" != "xx" ]
 	then
 		echo ""
-		echo "ERROR: Failed to fully mount $client"
-		echo "See bri -s $client"
+		echo "ERROR: $stratum already has mounts, refusing to continue." >&2
+		echo "Consider alternative brs command, see \`brs --help\`" >&2
 		exit 1
 	fi
 
-	if [ "${2:-}" != "update" ]
-	then
-		out "[$cur/$max] Enabling $client: executing prepost..."
-		cur=$(expr $cur + 1)
-		for exe in $(bri -c $client postenable)
-		do
-			. $exe $client
-		done
-	fi
+	run_config preenable $stratum || return 1
+	mount_stratum $stratum || return 1
+	run_config postenable $stratum || return 1
 
-	out "[$cur/$max] Enabling $client: setting as enabled..."
-	cur=$(expr $cur + 1)
-	if [ -r "/bedrock/etc/clients.d/$client.conf" ]
-	then
-		if [ -r "/bedrock/etc/clients.d/$client.conf.disabled" ]
-		then
-			echo ""
-			echo "ERROR:"
-			echo "Config exists for both states:"
-			echo "    /bedrock/etc/clients.d/$client.conf"
-			echo "and"
-			echo "    /bedrock/etc/clients.d/$client.conf.disabled"
-			echo "This must be resolved manually."
-		else
-			echo " done"
-		fi
-	else
-		if [ -r "/bedrock/etc/clients.d/$client.conf.disabled" ]
-		then
-			mv /bedrock/etc/clients.d/$client.conf.disabled /bedrock/etc/clients.d/$client.conf
-			echo " done"
-		else
-			# Should be pretty unlikely this happens, but just in case.
-			echo ""
-			echo "ERROR:"
-			echo "No config exists."
-			echo "This must be resolved manually."
-		fi
-	fi
+	echo -n "$indent"
+	echo -n "Setting $stratum as enabled... "
+	touch /bedrock/run/enabled_strata/$stratum
+	for alias in $(bri -I | awk -v"stratum=$stratum" '$3 == stratum {print$1}')
+	do
+		ln -fs $stratum /bedrock/run/enabled_strata/$alias
+	done
+	echo "done"
 
-	# tell brp about the change
+	echo -n "$indent"
+	echo -n "Updating brpath... "
 	echo 1 > /bedrock/brpath/reparse_config
+	echo "done"
 }
 
-update() {
-	enable "$1" "update"
+fix() {
+	for stratum in $(bri -l)
+	do
+		if [ "$(bri -a init)" = "$(bri -a "$stratum")" ]
+		then
+			stratum_root=""
+		else
+			stratum_root="/bedrock/strata/$stratum"
+		fi
+		for mount in $(bri -m $stratum | awk '/.share\/expected: (union|bind)\/bad.$/{print$1}')
+		do
+			echo "$stratum_root/$mount was improperly set as shared, fixing"
+			mount --make-private "$stratum_root/$mount"
+		done
+		if [ -n "$(bri -M "$stratum")" ]
+		then
+			echo "${stratum} is missing mounts, fixing"
+			brs update "$stratum"
+		fi
+	done
 }
 
-# brs has to run in the core rather than a client, as the core will see the
-# mount points differently from any client.  Moreover, unlike clients, the core
-# cannot be taken down; if the user attempts to take down the client running
-# brs things could become problematic.
-if [ "$(bri -n)" != "bedrock" ]
+export PATH=/bedrock/sbin:/bedrock/bin:$PATH
+
+# brs has to run with init local context, as init will see mount points
+# differently from any other stratum.  Moreover, init cannot be taken down; this
+# slightly lessens concerns related to disabling a stratum while brs is running.
+if [ "$(bri -n)" != "$(bri -a init)" ]
 then
-	exec /bedrock/bin/brc bedrock $0 $@
+	exec /bedrock/bin/brc init $0 $@
+fi
+
+if [ -z "${1:-}" ]
+then
+	echo "brs: no command specified.  See \`brs -h\`."
+	exit 1
+fi
+
+if [ "$1" = "h" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ "$1" = "--help" ]
+then
+	help
+	return 0
 fi
 
 action="$1"
-shift
-while [ -n "${1:-}" ]
-do
-	if [ "$1" = "bedrock" ]
-	then
-		echo "Cannot enable/disable Bedrock Linux core"
-		shift
-		continue
-	fi
-	case "$action" in
-		"enable")
-			enable "$1";;
-		"reenable")
-			disable "$1" && enable "$1";;
-		"disable")
-			disable "$1";;
-		"update")
-			update "$1";;
-		*)
-			help
-			exit 1;;
-	esac
-	shift
-done
+if ! bri -a "$2" >/dev/null 2>&1
+then
+	echo "brs: no such stratum $1"
+	return 1
+fi
+stratum="$(bri a $2)"
+
+indent=""
+
+case "$action" in
+	"force-enable")
+		enable "$stratum" "force";;
+	"enable")
+		enable "$stratum";;
+	"reenable")
+		disable "$stratum" && enable "$stratum";;
+	"disable")
+		disable "$stratum";;
+	"update")
+		mount_stratum "$stratum";;
+	"mount")
+		mount_stratum "$stratum";;
+	"unmount"|"umount")
+		unmount_stratum "$stratum";;
+	"kill")
+		kill_procs "$stratum";;
+	"preenable")
+		run_config preenable "$stratum";;
+	"predisable")
+		run_config predisable "$stratum";;
+	"postenable")
+		run_config postenable "$stratum";;
+	"postdisable")
+		run_config postdisable "$stratum";;
+	"fix")
+		fix;;
+	*)
+		echo "brs: invalid command.  See \`brs -h\`."
+		exit 1;;
+esac
